# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributedNames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='created_at',
        ),
    ]
