# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributedNames', '0002_remove_name_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='notFound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='notFound',
            field=models.BooleanField(default=False),
        ),
    ]
